### ISSUE TITLE
iOS x64 fat static library

### ISSUE THREAD

**Issue by Byfon** [lukeredpath/libPusher#165]
Will be there a build to support new x64 architecture https://github.com/lukeredpath/libPusher/downloads
Thanks

**Comment by hamchapman** [comment]
@mweyamutsvene what's the problem you're encountering with the build script? It seems to be working fine for me

**Comment by Balaram-Singh** [comment]
XXXs-iMac:Scripts XXX$ ./build.sh 
Your Gemfile lists the gem rest-client (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Using rake 10.3.2
Using ZenTest 4.10.1
Using RubyInline 3.12.3
Using i18n 0.6.11
Using multi_json 1.10.1
Using activesupport 3.2.19
Using claide 0.4.0
Using fuzzy_match 2.0.4
Using json 1.8.1
Using nap 0.8.0
Using cocoapods-core 0.28.0
Using cocoapods-downloader 0.2.0
Using colored 1.2
Using escape 0.0.4
Using json_pure 1.8.1
Using open4 1.3.4
Using xcodeproj 0.14.1
Using cocoapods 0.28.0
Using daemons 1.1.9
Using eventmachine 1.0.3
Using highline 1.6.21
Using hirb 0.7.2
Using mime-types 2.3
Using netrc 0.7.7
Using rest-client 1.7.1
Using simpleconsole 0.1.1
Using github-downloads 0.1.3 from git://github.com/lukeredpath/github-downloads.git (at master)
Using httpclient 2.3.4.1
Using ios-sim-test 0.0.1 from git://github.com/alloy/ios-sim-test.git (at master)
Using systemu 2.6.4
Using macaddr 1.7.1
Using osx_keychain 1.0.0
Using signature 0.1.7
Using pusher 0.12.0
Using rack 1.5.2
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.5
Using state_machine 1.1.2
Using thin 1.6.2
Using uuid 2.3.7
Using xcodebuild-rb 0.2.0 from git://github.com/lukeredpath/xcodebuild-rb.git (at master)
Using bundler 1.7.2
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Your Gemfile lists the gem rest-client (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
(in /Users/XXX/Desktop/libPusher-master)
=> Running xcodebuild clean

Cleaning target: libPusher (in libPusher.xcproject)
===================================================

Configuration: Release
....................

Finished in 0.230744 seconds.
Clean succeeded.

=> Running xcodebuild build

Building target: libPusher (in libPusher.xcproject)
===================================================

Configuration: Release
...............................................................................................................

Finished in 2.406774 seconds.
Build succeeded.

.=> Running xcodebuild clean

Cleaning target: libPusher (in libPusher.xcproject)
===================================================

Configuration: Release
....................

Finished in 0.264629 seconds.
Clean succeeded.

=> Running xcodebuild build

Building target: libPusher (in libPusher.xcproject)
===================================================

Configuration: Release
...............................................................................................................

Finished in 2.311812 seconds.
Build succeeded.

.Creating fat binary from simulator and device builds...


When I use libPusher-combined.a I get the following error

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SRWebSocket", referenced from:
      objc-class-ref in libPusher-combined.a(PTPusherConnection.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

also
=======

XXXs-iMac:asd XXX$ lipo -info libPusher-combined.a 
Architectures in the fat file: libPusher-combined.a are: armv7 i386 x86_64 arm64 
XXXs-iMac:asd XXX$ lipo -thin i386 libPusher-combined.a -output libPusher-combined-i386.a
XXXs-iMac:asd XXX$ ar -t libPusher-combined-i386.a
__.SYMDEF
NSDictionary+QueryString.o
PTPusher.o
PTPusherEvent.o
NSString+Hashing.o
PTPusherChannel.o
PTPusherConnection.o
PTPusherEventDispatcher.o
PTTargetActionEventListener.o
PTBlockEventListener.o
PTPusherAPI.o
PTURLRequestOperation.o
PTPusherChannelAuthorizationOperation.o
PTJSON.o
PTPusherMockConnection.o
PTPusher+Testing.o

**Comment by lukeredpath** [comment]
Re: the above, the documentation should make this clearer but if you're using pre built static library, you need to manage the dependencies manually and add a copy of SocketRocket to your project. This is by design; I consider it bad practice for static libraries to embed copies of their dependencies as this can easily lead to duplicate symbol errors if multiple libraries contain the same dependencies. 

I would obviously recommend CocoaPods as this takes care of everything for you but if you can't use it, just drop SocketRocket into your project and make sure you've configured its dependencies too. 

I will try and update the wiki. 

The original issue is about 64 bit support and I intend to look at fixing this.

**Comment by lukeredpath** [comment]
Regarding 64 bit support - the latest HEAD builds with no warnings against iOS8 with 64 bit architecture so there's no reason why it shouldn't work.

If you clone the latest source you can run script/build.sh it should run without any problems.

For convenience I've decided to create a fat binary from the latest HEAD which I've published as a pre-release version of 1.6.

https://github.com/lukeredpath/libPusher/releases/tag/v1.6-alpha

Please let me know how you get on with this.

**Comment by zeroeth** [comment]
I can confirm 1.5 builds 64bit as well by updating the xcodebuild-rb gem and removing the .arch references in the Rakefile. You can use `lipo -info dist/libPusher/libPusher-combined.a` to verify your results.

**Comment by lukeredpath** [comment]
I'm going to close this as there is a build available. Keep an eye out for a final 1.6 release.
